### ISSUE TITLE
Flask Secret key

### ISSUE THREAD

**Issue by nickcj931** [juriansluiman/groceri.es#4]
Hello,

Never set this up before, could you please help with understanding how you get the Secret key for Flask? 
I am assuming I get the following error on docker run due to missing Secret Key for Flask...
[error.txt](https://github.com/juriansluiman/groceri.es/files/5789749/error.txt)

**Comment by Igor-Felipy** [comment]
You can define the secret key using: 
app.config['SECRET_KEY'] = 'Your Secret Key' 
or if you are using a config.py you just need put this line in the file: 
SECRET_KEY = 'Your Secret Key'

**Comment by nickcj931** [comment]
@Igor-Felipy thanks for the response. I am still rather confused, and it might be me being thick!

I dont understand where you get the 'Your Secret Key' from. How do you generate this?

**Comment by Igor-Felipy** [comment]
You can replace "Your Secret Key" for any word or phrase that you want, here: https://randomkeygen.com/ you can generate random keys for you application.
I made this application https://github.com/Igor-Felipy/Billy_Social-Network/blob/master/config.py and you can see how I implemented the secret_key.

**Comment by nickcj931** [comment]
Im clearly being stupid then haha thanks for putting me straight @Igor-Felipy !!
